services:
  app0:
    build:
      context: app
    network_mode: host
    environment:
      - APP_ID=app0
      - PORT=7000
  app1:
    build:
      context: app
    network_mode: host
    environment:
      - APP_ID=app1
      - PORT=7001
  app2:
    build:
      context: app
    network_mode: host
    environment:
      - APP_ID=app2
      - PORT=7002
  haproxy:
    container_name: haproxy
    image: haproxytech/haproxy-ubuntu:3.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./etc/haproxy:/usr/local/etc/haproxy
